const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char]));

export function shell(state) {
  const overview = state.snapshot?.overview;
  const branch = overview?.branch ?? "No branch";
  const base = overview?.base?.value ?? overview?.base ?? "Base not configured";
  return `<div class="shell"><aside class="sidebar"><div class="brand"><span aria-hidden="true">GH</span><strong>git helper</strong><small>safe Git workbench</small></div><button class="repo-picker" data-event="pick-repository"><span class="eyebrow">REPOSITORY</span><strong>${esc(overview?.name ?? "Open a repository")}</strong><code>${esc(overview?.path ?? "Desktop access required")}</code></button><nav aria-label="Primary navigation"><button class="nav-item ${state.view === "actions" ? "active" : ""}" data-view="actions" aria-current="${state.view === "actions" ? "page" : "false"}">Actions</button><button class="nav-item ${state.view === "saved" ? "active" : ""}" data-view="saved" aria-current="${state.view === "saved" ? "page" : "false"}">Saved work <span>${state.saved.length}</span></button><button class="nav-item ${state.view === "recovery" ? "active" : ""}" data-view="recovery" aria-current="${state.view === "recovery" ? "page" : "false"}">Recovery <span>${state.operations.length}</span></button></nav><div class="connection">${overview ? `<span class="dot good"></span>Git ${esc(overview.git_version)}` : `<span class="dot"></span>Browser mode`}</div></aside><section class="main"><header class="repo-bar"><div><span class="eyebrow">CURRENT BRANCH</span><strong>${esc(branch)}</strong></div><div><span class="eyebrow">BASE</span><strong>${esc(base)}</strong></div><div class="worktree"><span class="dot ${overview?.worktree?.conflicts ? "bad" : "good"}"></span>${overview ? `${overview.worktree.staged + overview.worktree.unstaged + overview.worktree.untracked} local changes` : "Repository unavailable"}</div><button class="secondary" data-event="refresh" aria-label="Refresh repository">Refresh</button></header><div id="workspace">${renderView(state)}</div><footer>${state.busy ? "Working…" : state.error ? esc(state.error) : "Ready"}</footer></section></div>`;
}

function renderView(state) { if (!state.snapshot) return `<section class="empty"><h1>Desktop repository access unavailable</h1><p>Open Git Helper as a Tauri desktop app to inspect a repository. No preview data is shown.</p><button class="primary" data-event="pick-repository">Choose repository</button></section>`; if (state.view === "saved") return savedView(state); if (state.view === "recovery") return recoveryView(state); return actionsView(state); }

function actionsView(state) {
  const tabs = [["uncommit", "Uncommit paths"], ["edit_message", "Edit message"], ["exclude_submodule", "Exclude submodule"], ["quick_switch", "Quick switch"], ["sync", "Sync"]];
  const baseChooser = state.snapshot.overview.base ? "" : `<div class="inline-warning">Base is missing. <select id="base-choice" aria-label="Remote Base ref"><option value="">Choose a remote ref</option>${state.baseChoices.map((choice) => `<option value="${esc(choice.reference.value ?? choice.reference)}">${esc(choice.display ?? choice.reference)}</option>`).join("")}</select> <button class="link" data-event="choose-base">Save Base</button></div>`;
  const result = state.outcome ? `<div class="result"><strong>${esc(state.outcome.headline)}</strong>${state.outcome.details.map((detail) => `<span>${esc(detail)}</span>`).join("")}${state.outcome.offer_force_push ? `<button class="primary" data-event="prepare-force-push">Review force push</button>` : ""}</div>` : "";
  const syncStatus = state.snapshot.overview.sync_status;
  const resumable = ["fetch", "base-merge-conflict", "wip-reapply-conflict"].includes(syncStatus);
  const syncLabel = syncStatus === "fetch" ? "Sync fetch was interrupted" : `Sync paused at ${esc(syncStatus)}`;
  const syncAction = resumable ? `<button class="link" data-event="prepare-resume">${syncStatus === "fetch" ? "Review retry" : "Review resume"}</button>` : `<button class="link" data-view="recovery">Inspect recovery</button>`;
  const syncResume = syncStatus ? `<div class="inline-warning"><strong>${syncLabel}</strong> ${syncAction}</div>` : "";
  return `<section class="workspace" id="workspace-panel" tabindex="-1"><div class="workspace-head"><div><span class="eyebrow accent">ACTIONS</span><h1>Review every change</h1><p>Select a Git object, inspect impact, then apply once.</p></div>${baseChooser}</div>${syncResume}${result}<div class="tabs" role="tablist">${tabs.map(([id, label]) => `<button role="tab" aria-controls="workspace-panel" aria-selected="${state.operation === id}" data-operation="${id}">${label}</button>`).join("")}</div>${state.review ? reviewView(state) : operationForm(state)}</section>`;
}

function operationForm(state) {
  const base = state.snapshot.overview.base?.value ?? state.snapshot.overview.base ?? "";
  if (state.operation === "uncommit") return `<form data-form="uncommit"><label>Base ref<select name="base" required><option value="${esc(base)}">${esc(base || "Choose a Base first")}</option></select></label><label>Changed paths<input name="query" placeholder="Search paths" data-event="filter-paths" /><select name="paths" multiple size="6" aria-label="Changed paths">${state.paths.map((p) => `<option value="${esc(p.path.value ?? p.path)}">${esc(p.status)} ${esc(p.path.value ?? p.path)}</option>`).join("")}</select></label><button class="primary" type="submit" ${!base || !state.paths.length ? "disabled" : ""}>Review uncommit</button></form>`;
  if (state.operation === "edit_message") return `<form data-form="edit_message"><label>Commit<select name="commit" required>${state.commits.map((c) => `<option value="${esc(c.id.value ?? c.id)}">${esc(c.short_id)} — ${esc(c.subject)} (${esc(c.author.name)})</option>`).join("")}</select></label><label>New full message<textarea name="message" rows="8" required>${esc(state.commits[0]?.message ?? "")}</textarea></label><button class="primary" type="submit" ${!state.commits.length ? "disabled" : ""}>Review message edit</button></form>`;
  if (state.operation === "exclude_submodule") return `<form data-form="exclude_submodule"><label>Submodule<select name="path" required>${state.submodules.map((s) => `<option value="${esc(s.path.value ?? s.path)}">${esc(s.path.value ?? s.path)} · ${esc(s.object)}</option>`).join("")}</select></label><label class="check"><input type="checkbox" name="install_hook" checked /> Install exclusion hook</label><label class="check"><input type="checkbox" name="disable_recurse" /> Disable recurse-submodules</label><button class="primary" type="submit" ${!state.submodules.length ? "disabled" : ""}>Review exclusion</button></form>`;
  if (state.operation === "quick_switch") return `<form data-form="quick_switch"><label>Local branch<select name="target_branch" required>${state.branches.map((b) => `<option value="${esc(b.name)}">${esc(b.name)}${b.saved_work ? " · saved work" : ""}</option>`).join("")}</select></label><button class="primary" type="submit" ${!state.branches.length ? "disabled" : ""}>Review switch</button></form>`;
  if (state.operation === "force_push") return `<div class="empty-copy"><p>Force push is only available after a successful rewrite.</p><button class="primary" data-event="prepare-force-push">Review force push</button></div>`;
  return `<form data-form="sync"><label>Base ref<select name="base" required><option value="${esc(base)}">${esc(base || "Choose a Base first")}</option></select></label><button class="primary" type="submit" ${!base ? "disabled" : ""}>Review sync</button></form>`;
}

function reviewView(state) { const r = state.review; return `<section class="review" aria-labelledby="review-title"><span class="eyebrow accent">REVIEW</span><h2 id="review-title">${esc(r.title)}</h2><div class="review-grid"><div><h3>Impact</h3><ul>${r.impact.map((x) => `<li>${esc(x)}</li>`).join("")}</ul></div><div><h3>Preserved</h3><ul>${r.preserves.map((x) => `<li>${esc(x)}</li>`).join("")}</ul></div></div>${r.warnings.length ? `<div class="warning"><strong>Warnings</strong><ul>${r.warnings.map((x) => `<li>${esc(x)}</li>`).join("")}</ul></div>` : ""}<h3>Exact commands</h3><pre>${esc(r.commands.join("\n"))}</pre><div class="review-actions"><button class="secondary" data-event="cancel-review">Cancel</button><button class="primary" data-event="apply-review">${esc(r.apply_label)}</button></div></section>`; }

function savedView(state) { const branch = state.snapshot.overview.branch; return `<section class="workspace"><div class="workspace-head"><span class="eyebrow accent">SAVED WORK</span><h1>Snapshots from live data</h1></div><div class="data-list">${state.saved.length ? state.saved.map((item) => `<article><div><strong>${esc(item.branch)}</strong><code>${esc(item.reference)} · ${esc(item.snapshot)}</code></div><button class="secondary" data-saved-restore="${esc(item.branch)}" ${item.branch === branch ? "" : "disabled"}>${item.branch === branch ? "Restore" : "Arrive on branch to restore"}</button><button class="danger" data-saved-delete="${esc(item.branch)}" data-saved-snapshot="${esc(item.snapshot)}">Delete</button></article>`).join("") : `<p class="empty-copy">No saved work for this repository.</p>`}</div></section>`; }
function recoveryView(state) { return `<section class="workspace"><div class="workspace-head"><span class="eyebrow accent">RECOVERY</span><h1>Recorded safety net</h1><p>Ref recovery does not restore the worktree.</p></div><div class="data-list">${state.operations.length ? state.operations.map((item) => `<article><div><strong>${esc(item.operation)}</strong><code>${esc(item.id)} · ${esc(item.phase ?? (item.finished ? "completed" : "incomplete"))}</code></div><button class="secondary" data-copy="${esc(item.recovery_command ?? "")}" ${item.recovery_command ? "" : "disabled"}>Copy command</button></article>`).join("") : `<p class="empty-copy">No recorded operations.</p>`}</div></section>`; }
